name: .NET

on:
  push:
    branches: [ tribe ]
  pull_request:
    branches: [ tribe ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - uses: actions/upload-artifact@v2
      with:
        name: test_report
        path: /home/runner/work/RevolveUavcan/RevolveUavcan/RevolveUavcanTest/TestResults/test-results.trx
    - uses: dorny/test-reporter@v1.4.3
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Unit Tests            # Name of the check run which will be created
          path: /home/runner/work/RevolveUavcan/RevolveUavcan/RevolveUavcanTest/TestResults/test-results.trx    # Path to test results
          reporter: dotnet-trx        # Format of test results