name: Build & Test

on:
  push:
    branches: [ tribe ]
  pull_request:
    branches: [ tribe ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - name : coverlet
      uses: b3b00/coverlet-action@1.1.0
      with:
        testProject: 'RevolveUavcanTest/RevolveUavcanTest.csproj'
        output: 'lcov.info'
        outputFormat: 'lcov'
        excludes: '[program]*,[test]test.*'

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: test_report
        path: /home/runner/work/RevolveUavcan/RevolveUavcan/RevolveUavcanTest/TestResults/test-results.trx
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: coverage_report
        path: /home/runner/work/RevolveUavcan/RevolveUavcan/RevolveUavcanTest/lcov.info
    - uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN }} 
        path-to-lcov: /home/runner/work/RevolveUavcan/RevolveUavcan/RevolveUavcanTest/lcov.info
    - name: Test Reporter
      uses: dorny/test-reporter@v1.4.3
      if: ${{ always() }}
      with:
        name: Test Report            # Name of the check run which will be created
        path: /home/runner/work/RevolveUavcan/RevolveUavcan/RevolveUavcanTest/TestResults/test-results.trx    # Path to test results
        reporter: dotnet-trx        # Format of test results