name: Build NuGet package
on:
  push:
    tags:
      - "v*.*.*.*"

jobs:
  publish:
    name: build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - run: nuget spec
      - run: nuget pack RevolveUavcan/RevolveUavcan.csproj -Version "${{ github.ref }}".substring(11)

      - uses: actions/upload-artifact@v2
        with:
          name: test_report
          path: /home/runner/work/RevolveUavcan/RevolveUavcan/*.nupkg