name: Build NuGet package
on:
  push:
    branches: [ tribe ]

jobs:
  publish:
    name: build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - run: nuget spec
      - run: nuget pack RevolveUavcan/RevolveUavcan.csproj