name: Build and Release NuGet package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

      - name: Extract version from tag
        run: |
          # remove the `refs/tags/v`
          Release_Version=$(echo ${{ github.ref }}| cut -d'v' -f 1)
          # Ensure file is written in UTF8
          echo "RELEASE_VERSION=$Release_Version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: RevolveUavcan/RevolveUavcan.csproj
          PACKAGE_NAME: RevolveUavcan
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: false
          VERSION_STATIC: $env:RELEASE_VERSION